---
kind: pkgfile.Build
spec:
  targets:
    - talos-sbc-rk356x-mainline
    - talos-kernel-rk356x-mainline
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
    - KERNEL_VARIANT
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: PKGS
        defaultValue: v1.7.0
      - name: KERNEL_VARIANT
        defaultValue: mainline
---
kind: common.Build
spec:
    ignoredPaths:
      - go.work.sum
