# commit to be tagged for the new release
commit = "HEAD"

project_name = "talos-sbc-rk3588"
github_repo = "milas/talos-sbc-rk3588"
match_deps = "^github.com/(milas/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
