# commit to be tagged for the new release
commit = "HEAD"

project_name = "talos-sbc-rk356x"
github_repo = "alabruna/talos-sbc-rk356x"
match_deps = "^github.com/(alabruna/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
